// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIJZgmMUuz9tE7979iEFp_riSiGRjOpsY',
    appId: '1:433238092555:web:b721f3703c3a105e3d900e',
    messagingSenderId: '433238092555',
    projectId: 'tesla-ae311',
    authDomain: 'tesla-ae311.firebaseapp.com',
    storageBucket: 'tesla-ae311.appspot.com',
    measurementId: 'G-NNJVSTX237',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXzKvCjTlSIeQaBW2NN9dDt3A-XzfpPhk',
    appId: '1:433238092555:android:d848b5b9f01c5d943d900e',
    messagingSenderId: '433238092555',
    projectId: 'tesla-ae311',
    storageBucket: 'tesla-ae311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIRfT-TVGWK9ZjqgHQz9Av0EAZINbc1_g',
    appId: '1:433238092555:ios:032a1d5581937dd73d900e',
    messagingSenderId: '433238092555',
    projectId: 'tesla-ae311',
    storageBucket: 'tesla-ae311.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIRfT-TVGWK9ZjqgHQz9Av0EAZINbc1_g',
    appId: '1:433238092555:ios:032a1d5581937dd73d900e',
    messagingSenderId: '433238092555',
    projectId: 'tesla-ae311',
    storageBucket: 'tesla-ae311.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIJZgmMUuz9tE7979iEFp_riSiGRjOpsY',
    appId: '1:433238092555:web:5b6289db54928b603d900e',
    messagingSenderId: '433238092555',
    projectId: 'tesla-ae311',
    authDomain: 'tesla-ae311.firebaseapp.com',
    storageBucket: 'tesla-ae311.appspot.com',
    measurementId: 'G-6W32R9WR35',
  );

}